packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
  - 'utils/*'
  - 'app/*'
  - 'e2e'
  - 'e2e/demos/*'
allowBuilds:
  esbuild: true
  nx: true
minimumReleaseAgeExclude:
  - 'changesets-toolkit@0.1.0-beta.0 || 0.1.0'
