#!/usr/bin/env node
"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
Object.defineProperty(exports, "__esModule", { value: true });
const minimist = require('minimist');
const execa = require('execa');
const helper_1 = require("../helper");
const argv = minimist(process.argv.slice(2));
function main() {
    return __awaiter(this, void 0, void 0, function* () {
        helper_1.logger.info('start publishing...');
        if (argv['git-tag'] === false) {
            yield execa('npx', ['changeset', 'publish', '--no-git-tag'], { stdio: 'inherit' });
        }
        else {
            yield execa('npx', ['changeset', 'publish'], { stdio: 'inherit' });
            helper_1.logger.info('git push --follow-tags...');
            yield execa('git', ['push', '--follow-tags'], { stdio: 'inherit' });
        }
        helper_1.logger.info('publish successfully');
    });
}
main().catch((error) => {
    helper_1.logger.error('Failed to publish:', error);
    process.exit(1);
});
