#!/usr/bin/env node
"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
Object.defineProperty(exports, "__esModule", { value: true });
const fs = __importStar(require("node:fs"));
const path = __importStar(require("node:path"));
const fg = __importStar(require("fast-glob"));
const micromatch = __importStar(require("micromatch"));
const minimist = require('minimist');
const execa = require('execa');
const helper_1 = require("../helper");
const argv = minimist(process.argv.slice(2));
const rootDir = process.cwd();
const rootChangesetPre = path.join(rootDir, '.changeset', 'pre.json');
const BETA_PREFIX = 'beta';
const isPush = argv['git-push'] === true;
function deletePreJsonIfExists() {
    return __awaiter(this, void 0, void 0, function* () {
        if (fs.existsSync(rootChangesetPre)) {
            yield execa('rm', ['.changeset/pre.json'], { stdio: 'inherit' });
            helper_1.logger.info('deleted pre.json');
        }
    });
}
function bumpVersionForBeta(fn) {
    return __awaiter(this, void 0, void 0, function* () {
        helper_1.logger.info('start bumping beta version...');
        yield deletePreJsonIfExists();
        yield execa('npx', ['changeset', 'pre', 'enter', BETA_PREFIX], { stdio: 'inherit' });
        yield execa('npx', ['changeset', 'version'], { stdio: 'inherit' });
        fn();
        isPush && (yield (0, helper_1.gitPush)());
        helper_1.logger.success('bump version successfully');
    });
}
function bumpVersionForRelease(fn) {
    return __awaiter(this, void 0, void 0, function* () {
        helper_1.logger.info('start bumping release version...');
        yield deletePreJsonIfExists();
        yield execa('npx', ['changeset', 'version'], { stdio: 'inherit' });
        fn();
        isPush && (yield (0, helper_1.gitPush)());
        helper_1.logger.success('bump version successfully');
    });
}
function hiddenChangesets() {
    if (!argv.filter)
        return () => { };
    const mdRegex = /\s*---([\s\S]*?)\n\s*---(\s*(?:\n|$)[\s\S]*)/;
    const changesetPaths = fg
        .sync(`${path.join(process.cwd(), '.changeset')}/*.md`, { onlyFiles: true })
        .filter((file) => !file.startsWith('.') && file.endsWith('.md') && !file.endsWith('README.md'));
    const needHiddenPaths = changesetPaths.reduce((acc, filePath) => {
        const content = fs.readFileSync(filePath, { encoding: 'utf-8' });
        const match = mdRegex.exec(content);
        if (!match)
            return acc;
        const [_, roughRelease] = match;
        if (micromatch.contains(roughRelease, argv.filter)) {
            helper_1.logger.info(`filePath:${filePath} is matched`);
            return acc;
        }
        acc.push(filePath);
        return acc;
    }, []);
    helper_1.logger.info('needHiddenPaths', needHiddenPaths);
    const mdxFiles = needHiddenPaths.map((filePath) => {
        const replaceFilePath = filePath.replace('.md', '.mdx');
        fs.renameSync(filePath, replaceFilePath);
        return replaceFilePath;
    });
    return () => {
        mdxFiles.forEach((filePath) => fs.renameSync(filePath, filePath.replace('.mdx', '.md')));
    };
}
function main() {
    return __awaiter(this, void 0, void 0, function* () {
        const restore = hiddenChangesets();
        const bumpVersionFn = argv.beta ? bumpVersionForBeta.bind(null, restore) : bumpVersionForRelease.bind(null, restore);
        yield bumpVersionFn();
    });
}
main().catch((error) => {
    helper_1.logger.error('Failed to execute:', error);
    process.exit(1);
});
