export const ChineseSchools = [
	'安徽大学-安徽, 合肥, 本科',
	'中国科学技术大学-安徽, 合肥, 本科',
	'合肥工业大学-安徽, 合肥, 本科',
	'北京大学-北京, 北京, 本科',
	'中国人民大学-北京, 北京, 本科',
	'清华大学-北京, 北京, 本科',
	'北京交通大学-北京, 北京, 本科',
	'北京工业大学-北京, 北京, 本科',
	'北京航空航天大学-北京, 北京, 本科',
	'北京理工大学-北京, 北京, 本科',
	'北京科技大学-北京, 北京, 本科',
	'北京化工大学-北京, 北京, 本科',
	'北京邮电大学-北京, 北京, 本科',
	'中国农业大学-北京, 北京, 本科',
	'北京林业大学-北京, 北京, 本科',
	'北京协和医学院-北京, 北京, 本科',
	'北京中医药大学-北京, 北京, 本科',
	'北京师范大学-北京, 北京, 本科',
	'首都师范大学-北京, 北京, 本科',
	'北京外国语大学-北京, 北京, 本科',
	'中国传媒大学-北京, 北京, 本科',
	'中央财经大学-北京, 北京, 本科',
	'对外经济贸易大学-北京, 北京, 本科',
	'外交学院-北京, 北京, 本科',
	'中国人民公安大学-北京, 北京, 本科',
	'北京体育大学-北京, 北京, 本科',
	'中央音乐学院-北京, 北京, 本科',
	'中国音乐学院-北京, 北京, 本科',
	'中央美术学院-北京, 北京, 本科',
	'中央戏剧学院-北京, 北京, 本科',
	'中央民族大学-北京, 北京, 本科',
	'中国政法大学-北京, 北京, 本科',
	'华北电力大学-北京, 北京, 本科',
	'中国矿业大学（北京）-北京, 北京, 本科',
	'中国石油大学（北京）-北京, 北京, 本科',
	'中国地质大学（北京）-北京, 北京, 本科',
	'中国科学院大学-北京, 北京, 本科',
	'厦门大学-福建, 厦门, 本科',
	'福州大学-福建, 福州, 本科',
	'福建理工大学-福建, 福州, 本科',
	'兰州大学-甘肃, 兰州, 本科',
	'中山大学-广东, 广州, 本科',
	'暨南大学-广东, 广州, 本科',
	'华南理工大学-广东, 广州, 本科',
	'华南农业大学-广东, 广州, 本科',
	'广州医科大学-广东, 广州, 本科',
	'广州中医药大学-广东, 广州, 本科',
	'华南师范大学-广东, 广州, 本科',
	'南方科技大学-广东, 深圳, 本科',
	'广西大学-广西, 南宁, 本科',
	'贵州大学-贵州, 贵阳, 本科',
	'海南大学-海南, 海口, 本科',
	'河北工业大学-河北, 天津, 本科',
	'郑州大学-河南, 郑州, 本科',
	'河南大学-河南, 开封, 本科',
	'哈尔滨工业大学,-龙江, 哈尔滨, 本科',
	'哈尔滨工程大学,-龙江, 哈尔滨, 本科',
	'东北农业大学,-龙江, 哈尔滨, 本科',
	'东北林业大学,-龙江, 哈尔滨, 本科',
	'武汉大学-湖北, 武汉, 本科',
	'华中科技大学-湖北, 武汉, 本科',
	'中国地质大学（武汉）-湖北, 武汉, 本科',
	'武汉理工大学-湖北, 武汉, 本科',
	'华中农业大学-湖北, 武汉, 本科',
	'华中师范大学-湖北, 武汉, 本科',
	'中南财经政法大学-湖北, 武汉, 本科',
	'湘潭大学-湖南, 湘潭, 本科',
	'湖南大学-湖南, 长沙, 本科',
	'中南大学-湖南, 长沙, 本科',
	'湖南师范大学-湖南, 长沙, 本科',
	'国防科技大学-湖南, 长沙, 本科',
	'吉林大学-吉林, 长春, 本科',
	'延边大学-吉林, 延边, 本科',
	'东北师范大学-吉林, 长春, 本科',
	'南京大学-江苏, 南京, 本科',
	'苏州大学-江苏, 苏州, 本科',
	'东南大学-江苏, 南京, 本科',
	'南京航空航天大学-江苏, 南京, 本科',
	'南京理工大学-江苏, 南京, 本科',
	'中国矿业大学-江苏, 徐州, 本科',
	'南京邮电大学-江苏, 南京, 本科',
	'河海大学-江苏, 南京, 本科',
	'江南大学-江苏, 无锡, 本科',
	'南京林业大学-江苏, 南京, 本科',
	'南京信息工程大学-江苏, 南京, 本科',
	'南京农业大学-江苏, 南京, 本科',
	'南京医科大学-江苏, 南京, 本科',
	'南京中医药大学-江苏, 南京, 本科',
	'中国药科大学-江苏, 南京, 本科',
	'南京师范大学-江苏, 南京, 本科',
	'南昌大学-江西, 南昌, 本科',
	'辽宁大学-辽宁, 沈阳, 本科',
	'大连理工大学-辽宁, 大连, 本科',
	'东北大学-辽宁, 沈阳, 本科',
	'大连海事大学-辽宁, 大连, 本科',
	'内蒙古大学,-蒙古, 呼和浩特, 本科',
	'宁夏大学-宁夏, 银川, 本科',
	'青海大学-青海, 西宁, 本科',
	'山东大学-山东, 济南, 本科',
	'中国海洋大学-山东, 青岛, 本科',
	'中国石油大学（华东）-山东, 青岛, 本科',
	'山西大学-山西, 太原, 本科',
	'太原理工大学-山西, 太原, 本科',
	'西北大学-陕西, 西安, 本科',
	'西安交通大学-陕西, 西安, 本科',
	'西北工业大学-陕西, 西安, 本科',
	'西安电子科技大学-陕西, 西安, 本科',
	'长安大学-陕西, 西安, 本科',
	'西北农林科技大学-陕西, 咸阳, 本科',
	'陕西师范大学-陕西, 西安, 本科',
	'空军军医大学-陕西, 西安, 本科',
	'复旦大学-上海, 上海, 本科',
	'同济大学-上海, 上海, 本科',
	'上海交通大学-上海, 上海, 本科',
	'华东理工大学-上海, 上海, 本科',
	'东华大学-上海, 上海, 本科',
	'上海海洋大学-上海, 上海, 本科',
	'上海中医药大学-上海, 上海, 本科',
	'华东师范大学-上海, 上海, 本科',
	'上海外国语大学-上海, 上海, 本科',
	'上海财经大学-上海, 上海, 本科',
	'上海体育大学-上海, 上海, 本科',
	'上海音乐学院-上海, 上海, 本科',
	'上海大学-上海, 上海, 本科',
	'上海科技大学-上海, 上海, 本科',
	'海军军医大学-上海, 上海, 本科',
	'四川大学-四川, 成都, 本科',
	'西南交通大学-四川, 成都, 本科',
	'电子科技大学-四川, 成都, 本科',
	'西南石油大学-四川, 成都, 本科',
	'成都理工大学-四川, 成都, 本科',
	'四川农业大学-四川, 雅安, 本科',
	'成都中医药大学-四川, 成都, 本科',
	'西南财经大学-四川, 成都, 本科',
	'南开大学-天津, 天津, 本科',
	'天津大学-天津, 天津, 本科',
	'天津工业大学-天津, 天津, 本科',
	'天津医科大学-天津, 天津, 本科',
	'天津中医药大学-天津, 天津, 本科',
	'西藏大学-西藏, 拉萨, 本科',
	'新疆大学-新疆, 乌鲁木齐, 本科',
	'石河子大学-新疆, 石河子, 本科',
	'云南大学-云南, 昆明, 本科',
	'浙江大学-浙江, 杭州, 本科',
	'中国美术学院-浙江, 杭州, 本科',
	'宁波大学-浙江, 宁波, 本科',
	'重庆大学-重庆, 重庆, 本科',
	'西南大学-重庆, 重庆, 本科',
]

const ForeignSchools = [
	'Massachusetts Institute of Technology (MIT) USA, Massachusetts - 美国，马萨诸塞州，麻省理工学院',
	'Stanford University USA, California - 美国，加利福尼亚州，斯坦福大学',
	'Harvard University USA, Massachusetts - 美国，马萨诸塞州，哈佛大学',
	'California Institute of Technology (Caltech) USA, California - 美国，加利福尼亚州，加州理工学院',
	'University of Oxford UK, Oxford - 英国，牛津，牛津大学',
	'ETH Zurich Switzerland, Zurich - 瑞士，苏黎世，苏黎世联邦理工学院',
	'University of Cambridge UK, Cambridge - 英国，剑桥，剑桥大学',
	'Imperial College London UK, London - 英国，伦敦，伦敦帝国学院',
	'University of Chicago USA, Illinois - 美国，伊利诺伊州，芝加哥大学',
	'University College London (UCL) UK, London - 英国，伦敦，伦敦大学学院',
	'National University of Singapore (NUS) Singapore - 新加坡，新加坡国立大学',
	'Nanyang Technological University (NTU) Singapore - 新加坡，南洋理工大学',
	'University of Pennsylvania USA, Pennsylvania - 美国，宾夕法尼亚州，宾夕法尼亚大学',
	'EPFL Switzerland, Lausanne - 瑞士，洛桑，洛桑联邦理工学院',
	'Yale University USA, Connecticut - 美国，康涅狄格州，耶鲁大学',
	'University of Edinburgh UK, Edinburgh - 英国，爱丁堡，爱丁堡大学',
	'Columbia University USA, New York - 美国，纽约州，哥伦比亚大学',
	'Princeton University USA, New Jersey - 美国，新泽西州，普林斯顿大学',
	'Cornell University USA, New York - 美国，纽约州，康奈尔大学',
	'University of Toronto Canada, Ontario - 加拿大，安大略省，多伦多大学',
	'University of Michigan USA, Michigan - 美国，密歇根州，密歇根大学',
	'Johns Hopkins University USA, Maryland - 美国，马里兰州，约翰霍普金斯大学',
	'University of Tokyo Japan, Tokyo - 日本，东京，东京大学',
	'Australian National University (ANU) Australia, Canberra - 澳大利亚，堪培拉，澳大利亚国立大学',
	"King's College London UK, London - 英国，伦敦，伦敦国王学院",
	'University of Manchester UK, Manchester - 英国，曼彻斯特，曼彻斯特大学',
	'McGill University Canada, Quebec - 加拿大，魁北克省，麦吉尔大学',
	'University of California, Berkeley USA, California - 美国，加利福尼亚州，加州大学伯克利分校',
	'University of California, Los Angeles (UCLA) USA, California - 美国，加利福尼亚州，加州大学洛杉矶分校',
	'University of Hong Kong (HKU) Hong Kong - 香港，香港大学',
	'University of British Columbia Canada, British Columbia - 加拿大，不列颠哥伦比亚省，不列颠哥伦比亚大学',
	'University of Melbourne Australia, Victoria - 澳大利亚，维多利亚州，墨尔本大学',
	'University of Sydney Australia, New South Wales - 澳大利亚，新南威尔士州，悉尼大学',
	'Kyoto University Japan, Kyoto - 日本，京都，京都大学',
	'University of New South Wales (UNSW Sydney) Australia, New South Wales - 澳大利亚，新南威尔士州，新南威尔士大学',
	'University of Queensland Australia, Queensland - 澳大利亚，昆士兰州，昆士兰大学',
	'London School of Economics and Political Science (LSE) UK, London - 英国，伦敦，伦敦政治经济学院',
	'University of Warwick UK, Coventry - 英国，考文垂，华威大学',
	'University of Edinburgh UK, Edinburgh - 英国，爱丁堡，爱丁堡大学',
	'University of Amsterdam Netherlands, Amsterdam - 荷兰，阿姆斯特丹，阿姆斯特丹大学',
	'University of Glasgow UK, Glasgow - 英国，格拉斯哥，格拉斯哥大学',
	'University of Copenhagen Denmark, Copenhagen - 丹麦，哥本哈根，哥本哈根大学',
	'University of Bristol UK, Bristol - 英国，布里斯托尔，布里斯托大学',
	'University of Leeds UK, Leeds - 英国，利兹，利兹大学',
	'University of Southampton UK, Southampton - 英国，南安普顿，南安普顿大学',
	'University of Birmingham UK, Birmingham - 英国，伯明翰，伯明翰大学',
	'University of Nottingham UK, Nottingham - 英国，诺丁汉，诺丁汉大学',
	'University of Sheffield UK, Sheffield - 英国，谢菲尔德，谢菲尔德大学',
	'University of St Andrews UK, St Andrews - 英国，圣安德鲁斯，圣安德鲁斯大学',
	'University of Aberdeen UK, Aberdeen - 英国，阿伯丁，阿伯丁大学',
	'University of Liverpool UK, Liverpool - 英国，利物浦，利物浦大学',
	'University of York UK, York - 英国，约克，约克大学',
	'University of Sussex UK, Brighton - 英国，布莱顿，苏塞克斯大学',
	'University of Leicester UK, Leicester - 英国，莱斯特，莱斯特大学',
	'University of Reading UK, Reading - 英国，雷丁，雷丁大学',
	'University of Surrey UK, Guildford - 英国，吉尔福德，萨里大学',
	'University of Bath UK, Bath - 英国，巴斯，巴斯大学',

	'University of Dundee UK, Dundee - 英国，邓迪，邓迪大学',
	'University of Exeter UK, Exeter - 英国，埃克塞特，埃克塞特大学',
	'University of East Anglia UK, Norwich - 英国，诺里奇，东英吉利大学',
	'University of Kent UK, Canterbury - 英国，坎特伯雷，肯特大学',
	'University of Essex UK, Colchester - 英国，科尔切斯特，埃塞克斯大学',
	'University of Strathclyde UK, Glasgow - 英国，格拉斯哥，斯特拉斯克莱德大学',
	'University of Hull UK, Hull - 英国，赫尔，赫尔大学',
	'University of Stirling UK, Stirling - 英国，斯特灵，斯特灵大学',
	'University of Lincoln UK, Lincoln - 英国，林肯，林肯大学',
	'University of Plymouth UK, Plymouth - 英国，普利茅斯，普利茅斯大学',
	'University of Portsmouth UK, Portsmouth - 英国，朴茨茅斯，朴茨茅斯大学',
	'University of West England UK, Bristol - 英国，布里斯托尔，西英格兰大学',
	'University of Central Lancashire UK, Preston - 英国，普雷斯顿，中央兰开夏大学',
	'University of Hertfordshire UK, Hatfield - 英国，哈特菲尔德，赫特福德郡大学',
	'University of Greenwich UK, London - 英国，伦敦，格林威治大学',
	'University of Westminster UK, London - 英国，伦敦，威斯敏斯特大学',
	'University of Wolverhampton UK, Wolverhampton - 英国，伍尔弗汉普顿，伍尔弗汉普顿大学',
	'University of South Wales UK, Treforest - 英国，特雷福雷斯，南威尔士大学',
	'University of Huddersfield UK, Huddersfield - 英国，哈德斯菲尔德，哈德斯菲尔德大学',
	'University of Bedfordshire UK, Luton - 英国，卢顿，贝德福德大学',
	'University of Derby UK, Derby - 英国，德比，德比大学',
	'University of Chester UK, Chester - 英国，切斯特，切斯特大学',
	'University of Northampton UK, Northampton - 英国，北安普顿，北安普顿大学',
	'University of Bolton UK, Bolton - 英国，博尔顿，博尔顿大学',
	'University of Cumbria UK, Carlisle - 英国，卡莱尔，坎布里亚大学',
	'University of Sunderland UK, Sunderland - 英国，桑德兰，桑德兰大学',
	'University of Salford UK, Salford - 英国，索尔福德，索尔福德大学',
	'University of the West of Scotland UK, Paisley - 英国，佩斯利，西苏格兰大学',
	'University of Wales Trinity Saint David UK, Lampeter - 英国，兰彼得，威尔士三一圣大卫大学',
	'University of Buckingham UK, Buckingham - 英国，白金汉，白金汉大学',
	'University of St Mark & St John UK, Plymouth - 英国，普利茅斯，圣马克与圣约翰大学',
	'University of Suffolk UK, Ipswich - 英国，伊普斯威奇，萨福克大学',
	'University of Roehampton UK, London - 英国，伦敦，罗汉普顿大学',
	'University of Winchester UK, Winchester - 英国，温彻斯特，温彻斯特大学',
	'University of Chichester UK, Chichester - 英国，奇切斯特，奇切斯特大学',
	'University of East London UK, London - 英国，伦敦，东伦敦大学',
	'University of Greenwich UK, London - 英国，伦敦，格林威治大学',
	'University of West London UK, London - 英国，伦敦，西伦敦大学',
	'University of London UK, London - 英国，伦敦，伦敦大学',
	'University of Wales UK, Cardiff - 英国，卡迪夫，威尔士大学',
	'University of Ulster UK, Coleraine - 英国，科尔雷恩，阿尔斯特大学',
	'University of Birmingham UK, Birmingham - 英国，伯明翰，伯明翰大学',
	'University of Aberdeen UK, Aberdeen - 英国，阿伯丁，阿伯丁大学',
]

export const Schools = ChineseSchools.reduce<string[]>((acc, item, index) => {
	acc.push(item)
	if (ForeignSchools[index]) acc.push(ForeignSchools[index])
	return acc
}, []).map((item) => item.trim())
